name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install UV package manager
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install flake8 black isort mypy
        uv pip install python-telegram-bot psycopg2-binary pytz pytest
    
    - name: Run Black (code formatting check)
      run: |
        source .venv/bin/activate
        black --check --diff .
    
    - name: Run isort (import sorting check)
      run: |
        source .venv/bin/activate
        isort --check-only --diff .
    
    - name: Run flake8 (style and error checking)
      run: |
        source .venv/bin/activate
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Run mypy (type checking)
      run: |
        source .venv/bin/activate
        mypy --ignore-missing-imports --no-strict-optional *.py